In [14]:
import numpy as np

# sigmoid function
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))
    
# input dataset
X = np.array([  [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1] ])
    
# output dataset            
y = np.array([[0,0,1,1]]).T

# seed random numbers to make calculation
# deterministic (just a good practice)
np.random.seed(1)

# initialize weights randomly with mean 0
syn0 = 2*np.random.random((3,1)) - 1
print("initial syn0:")
print(syn0)
for iter in range(10000):
    
    # forward propagation
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))

    # how much did we miss?
    l1_error = y - l1

    # multiply how much we missed by the 
    
    # slope of the sigmoid at the values in l1
    l1_delta = l1_error * nonlin(l1,True)
    #nonlin(l1,True)為 l1之first order derivative

    # update weights
    syn0 += np.dot(l0.T,l1_delta)
    
    if(iter == 0):
        print ("Output before Training:")
        print (l1)
        print(l1_error)
    if(iter == 1):
        print ("Output on iter 1 Training:")
        print (l1)
        print(l1_error)
print ("Output After Training:")
print (l1)
print(l1_error)


initial syn0:
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
Output before Training:
[[0.2689864 ]
 [0.36375058]
 [0.23762817]
 [0.3262757 ]]
[[-0.2689864 ]
 [-0.36375058]
 [ 0.76237183]
 [ 0.6737243 ]]
Output on iter 1 Training:
[[0.29929909]
 [0.41433436]
 [0.32511054]
 [0.44378327]]
[[-0.29929909]
 [-0.41433436]
 [ 0.67488946]
 [ 0.55621673]]
Output After Training:
[[0.00966449]
 [0.00786506]
 [0.99358898]
 [0.99211957]]
[[-0.00966449]
 [-0.00786506]
 [ 0.00641102]
 [ 0.00788043]]
